---
title: "09-04-2020-stat-comp"
author: "Jikhan Jeong"
date: "9/4/2020"
output: html_document
---
# Random Number Generation by Inverse Transform
* Name: Jikhan Jeong
* Date: 09-04-2020
Ref: https://github.com/mariarizzo/SCR/tree/master/SCR-1e/SCR1e-code

```{r}
setwd("C:/Users/jikhan.jeong/Documents/R/0_stat_comp")
getwd()
```

```{r}
library(rmarkdown)
```

```{r}
rv <- sample(0:1, size =10, replace = TRUE); rv
```
```{r}
multinomial <- sample(1:3, size= 100, replace = TRUE, prob= c(0.2, 0.3, 0.5))
table(multinomial)
```


```{r}
x = seq(0,1, by=0.1);x
y = x^2
y[1:2]
hist(y)
```

```{r}
rnorm(10, 0,1) # normal distributin (size, mean, sd)
rt(10,2) # student t (size, degree of freedom)
```

equation arrays

\begin{eqnarray}
(a+b)^2 \\
a^2+2ab+b^2\\
\end{eqnarray}

### Inverse transform method, continuous case

f(x) = $3x^2$//
F(x) = $x^3$//
$F^{-1}(x) = u^{1/3}$//


```{r}
n <- 10
u <- runif(n)
x <- u^(1/3)
hist(x, prob=TRUE) # density histogram of sample from uniform
y <- seq(0,1, .01)
plot(y, 3*y^2)
hist(x, prob=TRUE, main = expression(f(x)==3*x^2))
```



```{r}
# 1. simulate from uniform
# 2. x = -1(1/lambda)* log(U)
lam =2
n = 100; U =runif(n)
E = -(1/lam)*log(U)
hist(E)
```

```{r}
# simulate Bernoulli(p) from a uniform distribution
p = 0.5
n = 100; U=runif(n)
x =ifelse(u<(1-p),0,1)

```

```{r}
# Gamma distribution
alpha = 2; beta =1; n=100
U = matrix(runif(n*alpha), alpha, n)
E = -log(U) # exp(l)
G = beta*colSums(E)
hist(G)

```

```{r}
gamma_rv_generation = function(nsim=1000, alpha=3, beta=2){
  U = matrix(runif(n*alpha), alpha, n)
  E = -log(U) # exp(l)
  G = beta*colSums(E)
  return (G)
  }
```

```{r}
x = gamma_rv_generation(10,4,0.5); hist(x)
```
```{r}
# Exponetial
lambda <-2
x <- -log(runif(10)/lambda);hist(x)
```

```{r}
# Two point distribution
# Bernoulli, p =0.4
n <- 10
p <- 0.4
u <- runif(n);u
x <- as.integer(u>.6);x
mean(x); var(x)

rbinom(n, size = 1, prob = p) # simple way
sample(c(0,1), size = n, replace = TRUE, prob = c(.6,.4))

```

